name: Periodic test
on:
  schedule:
    - cron: '0,20,40 * * * *'
jobs:
  update:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          date > date.txt
          git add date.txt
          git commit -m "Periodic test..."
          git push

